#docker-compose.ymlのバージョン
version: '3.8'
#docker volumeの設定
#volumes:
#  docker-volume:

#services以下に各コンテナの設定を書く
services:
  #Webサーバーのコンテナ
  web:
    image: nginx:1.18
    ports:
      - '8000:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  #アプリケーションのコンテナ
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
  #データベースのコンテナ
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: XXXX
      MYSQL_USER: XXXX
      MYSQL_PASSWORD: XXXXX
      MYSQL_ROOT_PASSWORD: XXXX
      TZ: 'Asia/Tokyo'
#    volumes:
#      - docker-volume:/var/lib/mysql
